# Generated by Django 5.1 on 2024-08-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Service_decs',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
