# Generated by Django 5.1 on 2024-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_service_service_decs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating_title', models.CharField(max_length=50)),
                ('Rating_decs', models.TextField(max_length=100)),
                ('Rating_image', models.FileField(default=None, max_length=250, null=True, upload_to='rating/')),
            ],
        ),
    ]
