# Generated by Django 5.1 on 2024-08-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='Rating_about',
            field=models.CharField(default='', max_length=50),
        ),
    ]
