# Generated by Django 5.1 on 2024-08-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_rating_rating_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Properties_name', models.CharField(max_length=50)),
                ('Properties_address', models.TextField()),
                ('Properties_price', models.CharField(max_length=20, null=True)),
                ('Properties_image', models.FileField(default=None, max_length=500, null=True, upload_to='Properties/')),
            ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='Rating_decs',
            field=models.TextField(),
        ),
    ]
