# Generated by Django 5.1 on 2024-08-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_properties_alter_rating_rating_decs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agents_name', models.CharField(max_length=50)),
                ('Agents_desc1', models.TextField()),
                ('Agents_desc2', models.TextField()),
            ],
        ),
    ]
