# Generated by Django 5.1 on 2024-08-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='Agents_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Agents/'),
        ),
    ]
