# Generated by Django 5.1 on 2024-08-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_agents_agents_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='Agents_desc2',
        ),
    ]
