# Generated by Django 5.1 on 2024-08-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='paragraph_text',
        ),
        migrations.AddField(
            model_name='about',
            name='About_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='About_desc1',
            field=models.TextField(),
        ),
    ]
