# Generated by Django 5.1 on 2024-08-27 09:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_remove_about_paragraph_text_about_about_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='About_desc2',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
