# Generated by Django 5.1 on 2024-08-27 09:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_about_about_desc2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='About_desc2',
        ),
        migrations.AlterField(
            model_name='about',
            name='About_desc1',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
