# Generated by Django 5.1 on 2024-08-27 09:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_remove_about_about_desc2_alter_about_about_desc1'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='About_Us1',
            field=ckeditor.fields.RichTextField(default=()),
        ),
        migrations.AddField(
            model_name='about',
            name='About_Us2',
            field=ckeditor.fields.RichTextField(default=()),
        ),
    ]
