# Generated by Django 5.1 on 2024-08-27 11:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_about_about_us1_about_about_us2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_name', models.CharField(max_length=50)),
                ('Team_desc', ckeditor.fields.RichTextField()),
                ('Team_rank', models.CharField(max_length=100)),
                ('Team_image', models.FileField(default=None, max_length=500, null=True, upload_to='team/')),
            ],
        ),
    ]
