# Generated by Django 5.1 on 2024-08-27 11:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Service_decs',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
