# Generated by Django 5.1 on 2024-08-28 10:14

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_service_service_decs'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='Properties_desc',
            field=ckeditor.fields.RichTextField(default=()),
        ),
        migrations.AddField(
            model_name='properties',
            name='Properties_image1',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='sub/'),
        ),
        migrations.AddField(
            model_name='properties',
            name='Properties_image2',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='sub/'),
        ),
        migrations.AddField(
            model_name='properties',
            name='Properties_image3',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='sub/'),
        ),
        migrations.AddField(
            model_name='properties',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='Home.agents'),
        ),
    ]
