# Generated by Django 5.1 on 2024-08-29 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_properties_properties_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Properties', to='Home.agents'),
        ),
    ]
