# Generated by Django 5.1 on 2024-09-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_alter_properties_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_name', models.CharField(max_length=50)),
                ('Images', models.FileField(default=None, max_length=250, null=True, upload_to='image/')),
            ],
        ),
    ]
