# Generated by Django 5.1 on 2024-09-02 05:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='Agents_desc1',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
