# Generated by Django 5.1 on 2024-09-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_alter_agents_agents_desc1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='About_image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='about/'),
        ),
    ]
