# Generated by Django 5.1 on 2024-09-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_alter_about_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='Agents_image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='Agents/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='Images',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='Properties_image',
            field=models.ImageField(default=None, max_length=500, null=True, upload_to='Properties/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='Properties_image1',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='sub/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='Properties_image2',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='sub/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='Properties_image3',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='sub/'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='Rating_image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='rating/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='Team_image',
            field=models.ImageField(default=None, max_length=500, null=True, upload_to='team/'),
        ),
    ]
