# Generated by Django 5.1 on 2024-09-02 07:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_alter_agents_agents_image_alter_image_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Rating_decs',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
