# Generated by Django 5.1 on 2024-09-04 09:26

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_alter_rating_rating_decs'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='Agents_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
