# Generated by Django 5.1 on 2024-09-04 09:38

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_agents_agents_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Team_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
